### ISSUE TITLE
most body's end with the closing body tag (</body>)

### ISSUE THREAD

**Issue by EddieTheEd** [Shan-Mei/shanmeis-notes#3]
as said in the title, most of the body paragraphs end with the body tag. Im guessing this is because you are literally writing html for jekyll?

solution: dont write html in .md files. or at least make them html files in the first place

</body>

**Comment by Shan-Mei** [comment]
It's only </body> because i've forgotteen to close the last thing.
i am still experimenting with he .HTML files.
