### ISSUE TITLE
a certain article has not been written

### ISSUE THREAD

**Issue by EddieTheEd** [Shan-Mei/shanmeis-notes#6]
(upon the request of chris chen)

https://shan-mei.github.io/shanmeis-notes/ranting/skirt-lengths

it has not been completed

complete so we can have a good laugh :)))

thanks
Ed (+chen)

**Comment by Shan-Mei** [comment]
Ahhh i was writing it on the train i just haven't pushed any changes sorry hahahaha

**Comment by EddieTheEd** [comment]
The article has been written
